version: "3.8"

services:
  server_minecraft:
    image: itzg/minecraft-server:latest
    container_name: "server_minecraft"
    ports:
    - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.19.2
      FORGEVERSION: 43.1.34
      ENABLE_ROLLING_LOGS: "true"
      DEBUG: "true"
      TZ: "Europe/Paris"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 10
      ONLINE_MODE: "FALSE"
      SERVER_NAME: "Nazarick-Kingdom"
      VIEW_DISTANCE: "32"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "4G"
    volumes:
    - ./data:/data
    - ./mods:/mods:ro
