version: "3.8"

services:
  server_minecraft:
    image: itzg/minecraft-server:latest
    container_name: "server_minecraft_neoforge"
    ports:
    - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: NEOFORGE
      VERSION: 1.20.1
      NEOFORGE_VERSION: 47.1.88
      ENABLE_ROLLING_LOGS: "true"
      DEBUG: "true"
      TZ: "Europe/Paris"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 10
      SERVER_NAME: "Nazarick-Kingdom"
      VIEW_DISTANCE: "32"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"
    volumes:
    - ./data:/data
    - ./mods:/mods:ro
